name: Tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      # We support Node Active LTS, Maintenance LTS, and Current. See
      # https://github.com/nodejs/release#release-schedule for release schedule.
      #
      # We test all supported Node versions on Linux, and the oldest and newest
      # on macOS/Windows. We use the latest images for each OS. See
      # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
      # for the latest available images.
      matrix:
        include:
          # Maintenance LTS (EOL 2026-04-30)
          - node: 20
            os: ubuntu-24.04
          - node: 20
            os: macos-15
          - node: 20
            os: windows-2022

          # Active LTS (EOL 2027-04-30)
          - node: 22
            os: ubuntu-24.04

          # Current (EOL 2025-06-01)
          - node: 23
            os: ubuntu-24.04
          - node: 23
            os: macos-15
          - node: 23
            os: windows-2022

      # Allow all matrix configurations to complete, instead of cancelling as
      # soon as one fails. Useful because we often have different kinds of
      # failures depending on the OS.
      fail-fast: false

    # Sometimes windows is far slower than the other OSs. Give it enough
    # time to complete if it's going to.
    timeout-minutes: 40
    runs-on: ${{ matrix.os }}

    env:
      WIREIT_LOGGER: 'quiet-ci'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - uses: google/wireit@setup-github-actions-caching/v2

      - run: npm ci

      # See https://code.visualstudio.com/api/working-with-extensions/continuous-integration#github-actions for why we need xvfb-run
      - run: npm test
        if: runner.os != 'Linux'
        # We run tests in parallel on Linux, but not on other OSs. This is
        # because the Mac and Windows runners are very flaky, and parallelism
        # makes them worse.
        env:
          WIREIT_PARALLEL: 1
      - run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - run: npm run test:cache-github-real

  lint-and-format:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run lint
      - run: npm run format:check
